### ISSUE TITLE
(Bug/erro) Na Node Modules

### ISSUE THREAD

**Issue by Vitordeabreu** [guiireal/sky-bot#6]
Estou enfrentando tal erro desde do príncipio, antes mesmo De instalar este Bot já sofria esse Erro, e Como já não bastasse, não foi diferente com o SKY-BKT, ocorreu o msm erro Quando eu o baixei, ao desenvolvedor @devgui, suba uma Node modules atualizada Por favor, agradeço.

By: Vitin Garotinho...

![Screenshot_20240924-101002](https://github.com/user-attachments/assets/d279cc86-baae-450a-bbe2-5becc7a84a5b)

**Comment by guiireal** [comment]
A node_modules foi atualizada!
